---
self-contained: true
title: Lab3
format:
   html:
      theme: cyborg
---

In [177]:
import pandas as pd
import numpy as np
from num2words import num2words

xmas = pd.read_csv('./Data/xmas.csv')
xmas.head()

   Day Day.in.Words  Gift.Item Verb Adjective        Location
0    1        first  partridge  NaN       NaN  in a pear tree
1    2       second       dove  NaN    turtle             NaN
2    3        third        hen  NaN    french             NaN
3    4       fourth       bird  NaN   calling             NaN
4    5        fifth       ring  NaN    golden             NaN

## Function 1

In [178]:
# Returns plural of a noun
def pluralize_gift(gift):
  if gift[-4:] == "oose":
    gift = gift[:-4] + "eese"
  elif gift[-1] == 'y':
    gift = gift[:-1] + "ies"
  else:
    gift += "s"

  return gift

In [179]:
assert pluralize_gift("goose") == "geese"
np.testing.assert_array_equal(xmas['Gift.Item'].apply(pluralize_gift), ['partridges', 'doves', 'hens', 'birds', 'rings', 'geese', 'swans',
       'maids', 'ladies', 'lords', 'pipers', 'drummers'])

## Function 2

In [180]:
# Takes as input the necessary information, and returns a phrase
def make_phrase(num, num_word, item, verb, adjective, location):
  verb = "" if pd.isna(verb) else verb
  adjective = "" if pd.isna(adjective) else adjective
  location = "" if pd.isna(location) else location

  if num > 1:
    item = pluralize_gift(item)
    num = num2words(num)
  elif item[0].lower() in ['a', 'e', 'i', 'o', 'u']:
    num = "an"
  else:
    num = "a"
    
  words = [str(num), adjective, item, verb, location]
  phrase = ' '.join(word for word in words if word)
  return phrase

In [181]:
assert make_phrase(num = 10, 
                   num_word = "ten", 
                   item = "lord", 
                   verb = "a-leaping", 
                   adjective = "", 
                   location = "") == 'ten lords a-leaping'

xmas['Full.Phrase'] = xmas.apply(lambda row: make_phrase(row['Day'], 
                                                         row['Day.in.Words'], 
                                                         row['Gift.Item'],
                                                         row['Verb'],
                                                         row['Adjective'],
                                                         row['Location']), axis=1)

xmas.head()

,Day,Day.in.Words,Gift.Item,Verb,Adjective,Location,Full.Phrase
0,1,first,partridge,NaN,NaN,in a pear tree,a partridge in a pear tree
1,2,second,dove,NaN,turtle,NaN,two turtle doves
2,3,third,hen,NaN,french,NaN,three french hens
3,4,fourth,bird,NaN,calling,NaN,four calling birds
4,5,fifth,ring,NaN,golden,NaN,five golden rings

## Function 3

In [189]:
# Takes in dataset, number of day, and phrase column, outputs whole song
def sing_day(dataset, num, phrase_col):
  num_word = num2words(num, to='ordinal')
  intro = "On the " + num_word + " day of Christmas, my true love sent to me:\n"
  
  gifts = ""
  for i in range(num - 1, -1, -1):
    gifts += dataset.iloc[i][phrase_col]
    if i == 1:
      gifts += ", and\n"
    else:
      gifts += ",\n"
  
  return intro + gifts[:-2] + "."

In [190]:
days = xmas.apply(lambda row: sing_day(xmas, row.name + 1, 'Full.Phrase'), axis=1)

# Print each day
for day in days:
    print(day + "\n")

On the first day of Christmas, my true love sent to me:
a partridge in a pear tree.

On the second day of Christmas, my true love sent to me:
two turtle doves, and
a partridge in a pear tree.

On the third day of Christmas, my true love sent to me:
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the fourth day of Christmas, my true love sent to me:
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the fifth day of Christmas, my true love sent to me:
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the sixth day of Christmas, my true love sent to me:
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the seventh day of Christmas, my true love sent to me:
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the eighth day of Christmas, my true love sent to me:
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the ninth day of Christmas, my true love sent to me:
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the tenth day of Christmas, my true love sent to me:
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the eleventh day of Christmas, my true love sent to me:
eleven pipers piping,
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the twelfth day of Christmas, my true love sent to me:
twelve drummers drumming,
eleven pipers piping,
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

In [191]:
xmas2 = pd.read_csv('./Data/xmas2.csv')

xmas2['Full.Phrase'] = xmas2.apply(lambda row: make_phrase(row['Day'], 
                                                           row['Day.in.Words'], 
                                                           row['Gift.Item'],
                                                           row['Verb'],
                                                           row['Adjective'],
                                                           row['Location']), axis=1)

days = xmas2.apply(lambda row: sing_day(xmas2, row.name + 1, 'Full.Phrase'), axis=1)

# Print each day
for day in days:
    print(day + "\n")

On the first day of Christmas, my true love sent to me:
an email from Cal Poly.

On the second day of Christmas, my true love sent to me:
two meal points, and
an email from Cal Poly.

On the third day of Christmas, my true love sent to me:
three lost pens,
two meal points, and
an email from Cal Poly.

On the fourth day of Christmas, my true love sent to me:
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the fifth day of Christmas, my true love sent to me:
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the sixth day of Christmas, my true love sent to me:
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the seventh day of Christmas, my true love sent to me:
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the eighth day of Christmas, my true love sent to me:
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the ninth day of Christmas, my true love sent to me:
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the tenth day of Christmas, my true love sent to me:
ten loads of laundry,
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the eleventh day of Christmas, my true love sent to me:
eleven friends goodbye-ing,
ten loads of laundry,
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the twelfth day of Christmas, my true love sent to me:
twelve hours sleeping,
eleven friends goodbye-ing,
ten loads of laundry,
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.